services:
  - name: swiftcart-web
    type: web
    runtime: python
    plan: starter
    region: oregon
    autoDeploy: true
    buildCommand: python -m pip install --upgrade pip && python -m pip install -r requirements.txt
    startCommand: sh start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "0"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: swiftcart-db
          property: connectionString
      - key: GUNICORN_BIND
        value: 0.0.0.0:$PORT
      - key: GUNICORN_WORKERS
        value: "4"
      - key: GUNICORN_THREADS
        value: "2"
      - key: GUNICORN_TIMEOUT
        value: "120"
      - key: GUNICORN_GRACEFUL_TIMEOUT
        value: "30"
      - key: GUNICORN_KEEPALIVE
        value: "5"

databases:
  - name: swiftcart-db
    plan: basic-256mb
    region: oregon
    databaseName: swiftcart
    user: swiftcart
    postgresMajorVersion: "17"
